services:
  db:
    image: postgres:17-alpine # или postgres:17-alpine, как у тебя было
    container_name: hrhelper_postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  web:
    build: . # Контекст сборки - текущая директория (где Dockerfile)
    container_name: hrhelper_django_app
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /app # Рабочая директория, где будет лежать manage.py
    volumes:
      # Синхронизирует текущую директорию проекта на хосте с /app в контейнере
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - POSTGRES_DB=${POSTGRES_DB} # Используем ту же переменную, что и для сервиса db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data: