# Generated by Django 4.2.21 on 2025-06-01 22:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название подразделения')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Краткое название')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Шифр')),
                ('min_grade', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Нижняя граница разряда (ЕТС)')),
                ('max_grade', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Верхняя граница разряда (ЕТС)')),
                ('allocated_units', models.PositiveIntegerField(default=0, verbose_name='Кол-во выделенных штатных единиц')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('marital_status', models.CharField(choices=[('SINGLE', 'Холост/Не замужем'), ('MARRIED', 'Женат/Замужем'), ('DIVORCED', 'Разведен(а)'), ('WIDOWED', 'Вдовец/Вдова')], max_length=10, verbose_name='Семейное положение')),
                ('position', models.CharField(max_length=150, verbose_name='Должность')),
                ('grade', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Разряд')),
                ('start_date', models.DateField(verbose_name='Дата начала работы')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания работы')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr_management.department', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Сотрудник (Кадр)',
                'verbose_name_plural': 'Сотрудники (Кадры)',
                'ordering': ['full_name'],
            },
        ),
    ]
