# Generated by Django 4.2.21 on 2025-06-01 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('full_name', 'birth_date')},
        ),
    ]
