# Generated by Django 4.2.21 on 2025-06-01 23:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0002_alter_employee_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название KPI')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Вес KPI (в долях от 1)')),
            ],
            options={
                'verbose_name': 'Показатель эффективности (KPI)',
                'verbose_name_plural': 'Показатели эффективности (KPI)',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='tariff_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Тарифная ставка (оклад)'),
        ),
        migrations.CreateModel(
            name='EmployeePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveIntegerField(verbose_name='Год периода')),
                ('period_month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Месяц периода')),
                ('planned_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Плановое значение')),
                ('actual_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Фактическое значение')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='hr_management.employee', verbose_name='Сотрудник')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_management.kpi', verbose_name='Показатель KPI')),
            ],
            options={
                'verbose_name': 'Результат KPI сотрудника',
                'verbose_name_plural': 'Результаты KPI сотрудников',
                'ordering': ['-period_year', '-period_month', 'employee', 'kpi'],
                'unique_together': {('employee', 'kpi', 'period_year', 'period_month')},
            },
        ),
        migrations.CreateModel(
            name='BonusCalculationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveIntegerField(verbose_name='Год периода')),
                ('period_month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Месяц периода')),
                ('total_bonus_pool', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Общий премиальный фонд (S)')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr_management.department', verbose_name='Подразделение (если бюджет по подразделениям)')),
            ],
            options={
                'verbose_name': 'Настройка расчета премий',
                'verbose_name_plural': 'Настройки расчета премий',
                'unique_together': {('department', 'period_year', 'period_month')},
            },
        ),
    ]
