# Generated by Django 4.2.21 on 2025-06-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0003_kpi_employee_tariff_rate_employeeperformance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='assigned_kpis',
            field=models.ManyToManyField(blank=True, related_name='assigned_to_employees', to='hr_management.kpi', verbose_name='Назначенные KPI'),
        ),
    ]
